import JSZip from "jszip";
import { saveAs } from "file-saver";

export const handleExport = async () => {
  const zip = new JSZip();

  zip.file("index.html", `<h1> Your Agency Website </h1>`);
  zip.file("styles.css", `body { font-family: Arial, sans-serif; }`);

  zip.file("brand.json", JSON.stringify({
    colors: {
      primary: "#FF5733",
      secondary: "#33C1FF"
    },
    fonts: {
      heading: "Arial, sans-serif",
      body: "Verdana, sans-serif"
    }
  }, null, 2));

  const logoSvgContent = `<svg>...</svg>`;
  zip.file("logo.svg", logoSvgContent);

  const instructions = `
CONGRATULATIONS ON YOUR NEW AGENCY!

Here are your files:
1. index.html - Your main website file.
2. styles.css - The styling for your website.
3. logo.svg   - Your scalable logo file.
4. brand.json - Your brand color and font settings.

---------------------------------------------------
HOW TO GO LIVE IN 30 SECONDS (FREE)
---------------------------------------------------
1. Do not try to open index.html on your computer yet.
2. Go to https://app.netlify.com/drop
3. Drag and drop this entire unzipped folder onto that page.
4. Netlify will give you a live link (e.g., distinctive-agency-123.netlify.app).

Good luck!
- Generated by Nodal
    `;
  zip.file("INSTRUCTIONS.txt", instructions.trim());

  try {
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, "Nodal_Agency_Pack.zip");
  } catch (error) {
    console.error("Failed to zip files:", error);
    alert("Could not create download. Please try again.");
  }
};
